In [326]:
import pandas as pd
import numpy as np

In [327]:
df = pd.read_csv(
    "../data/raw/evenements_openagenda_france.csv"
)

df.head()

,agenda_uid,agenda,event_uid,titre,description,date_debut,date_fin,date,lieu,ville,region,departement,pays,latitude,longitude,type_evenement
0,50100,"La classe, l'œuvre ! 2026",1298208,Art et Soleil : le Cyanotype,"La classe, l’œuvre !",NaN,NaN,"{'end': '2026-05-23T23:59:59.000+02:00', 'begi...",Musée Buffon,Montbard,NaN,NaN,NaN,47.624452,4.336899,{}
1,50100,"La classe, l'œuvre ! 2026",1873551,Eugène Martel,"La classe, l’œuvre !",NaN,NaN,"{'end': '2026-05-23T23:59:59.000+02:00', 'begi...",Musée Louis Vouland,Avignon,NaN,NaN,NaN,43.947254,4.800664,{}
2,50100,"La classe, l'œuvre ! 2026",2056850,En mode romain : la fibule ancêtre de l'épingl...,"La classe, l’œuvre !",NaN,NaN,"{'end': '2026-05-23T23:59:59.000+02:00', 'begi...",Musée Amphoralis,Sallèles-d'Aude,NaN,NaN,NaN,43.262209,2.945924,{}
3,50100,"La classe, l'œuvre ! 2026",2248297,"Mulotia, femme esclavée à l'île Maurice","La classe, l’œuvre !",NaN,NaN,"{'end': '2026-05-23T23:59:59.000+02:00', 'begi...",Musée et château royal de Blois,Blois,NaN,NaN,NaN,47.585445,1.331811,{}
4,50100,"La classe, l'œuvre ! 2026",2716271,Visite Flash « C’est moi le guide ! » (FR/EN),"La classe, l’œuvre !",NaN,NaN,"{'end': '2026-05-23T23:59:59.000+02:00', 'begi...",Frac Grand Large — Hauts-de-France,Dunkerque,NaN,NaN,NaN,51.048063,2.375820,{}

In [328]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 208010 entries, 0 to 208009
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   agenda_uid      208010 non-null  int64
 1   agenda          208010 non-null  str
 2   event_uid       208010 non-null  int64
 3   titre           207670 non-null  str
 4   description     207660 non-null  str
 5   date_debut      0 non-null       float64
 6   date_fin        0 non-null       float64
 7   date            208010 non-null  str
 8   lieu            207110 non-null  str
 9   ville           206700 non-null  str
 10  region          0 non-null       float64
 11  departement     0 non-null       float64
 12  pays            0 non-null       float64
 13  latitude        207110 non-null  float64
 14  longitude       207110 non-null  float64
 15  type_evenement  208010 non-null  str
dtypes: float64(7), int64(2), str(7)
memory usage: 25.4 MB

In [329]:
df = df.drop(
    columns=[
        "date_debut",
        "date_fin",
        "region",
        "departement",
        "pays"
    ]
)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 208010 entries, 0 to 208009
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   agenda_uid      208010 non-null  int64
 1   agenda          208010 non-null  str
 2   event_uid       208010 non-null  int64
 3   titre           207670 non-null  str
 4   description     207660 non-null  str
 5   date            208010 non-null  str
 6   lieu            207110 non-null  str
 7   ville           206700 non-null  str
 8   latitude        207110 non-null  float64
 9   longitude       207110 non-null  float64
 10  type_evenement  208010 non-null  str
dtypes: float64(2), int64(2), str(7)
memory usage: 17.5 MB

In [330]:
df.isna().sum()

agenda_uid           0
agenda               0
event_uid            0
titre              340
description        350
date                 0
lieu               900
ville             1310
latitude           900
longitude          900
type_evenement       0
dtype: int64

In [331]:
df = df.dropna(
    subset=[
        "titre",
        "description",
        "ville",
        "latitude",
        "longitude"
    ]
)

df.shape

(206400, 11)

In [332]:
df.isna().sum()

agenda_uid        0
agenda            0
event_uid         0
titre             0
description       0
date              0
lieu              0
ville             0
latitude          0
longitude         0
type_evenement    0
dtype: int64

In [333]:
df["event_uid"].duplicated().sum()

np.int64(185772)

In [334]:
df = df.drop_duplicates(
    subset="event_uid"
)

df.shape

(20628, 11)

In [335]:
df.info()

<class 'pandas.DataFrame'>
Index: 20628 entries, 0 to 20800
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   agenda_uid      20628 non-null  int64
 1   agenda          20628 non-null  str
 2   event_uid       20628 non-null  int64
 3   titre           20628 non-null  str
 4   description     20628 non-null  str
 5   date            20628 non-null  str
 6   lieu            20628 non-null  str
 7   ville           20628 non-null  str
 8   latitude        20628 non-null  float64
 9   longitude       20628 non-null  float64
 10  type_evenement  20628 non-null  str
dtypes: float64(2), int64(2), str(7)
memory usage: 1.9 MB

In [336]:
df["event_uid"].duplicated().sum()

np.int64(0)

In [337]:
(df["description"].str.strip() == "").sum()

np.int64(0)

In [338]:
(df["titre"].str.strip() == "").sum()

np.int64(0)

In [339]:
df["date"].head()

0    {'end': '2026-05-23T23:59:59.000+02:00', 'begi...
1    {'end': '2026-05-23T23:59:59.000+02:00', 'begi...
2    {'end': '2026-05-23T23:59:59.000+02:00', 'begi...
3    {'end': '2026-05-23T23:59:59.000+02:00', 'begi...
4    {'end': '2026-05-23T23:59:59.000+02:00', 'begi...
Name: date, dtype: str

In [340]:
df["date"] = (
    df["date"]
    .str.extract(r"'begin': '([^']+)'")[0]
)

df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce",
    utc=True,
    format="mixed"
)

In [341]:
# Convertir en datetime
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce",
    utc=True,
    format="mixed"
)


# Vérifications
print(df["date"].head())

print(
    df["date"]
    .dt.year
    .value_counts()
    .sort_index()
)

print(
    "Date min :",
    df["date"].min()
)

print(
    "Date max :",
    df["date"].max()
)

0   2026-05-23 15:00:00+00:00
1   2026-05-23 15:00:00+00:00
2   2026-05-23 15:00:00+00:00
3   2026-05-23 15:00:00+00:00
4   2026-05-23 15:00:00+00:00
Name: date, dtype: datetime64[us, UTC]
date
2016      81
2017     164
2018     209
2019     228
2020     179
2021     358
2022    1684
2023    2890
2024    2829
2025    4745
2026    7233
2027      28
Name: count, dtype: int64
Date min : 2016-05-26 07:00:00+00:00
Date max : 2027-07-07 09:00:00+00:00

In [342]:
df.head()

,agenda_uid,agenda,event_uid,titre,description,date,lieu,ville,latitude,longitude,type_evenement
0,50100,"La classe, l'œuvre ! 2026",1298208,Art et Soleil : le Cyanotype,"La classe, l’œuvre !",2026-05-23 15:00:00+00:00,Musée Buffon,Montbard,47.624452,4.336899,{}
1,50100,"La classe, l'œuvre ! 2026",1873551,Eugène Martel,"La classe, l’œuvre !",2026-05-23 15:00:00+00:00,Musée Louis Vouland,Avignon,43.947254,4.800664,{}
2,50100,"La classe, l'œuvre ! 2026",2056850,En mode romain : la fibule ancêtre de l'épingl...,"La classe, l’œuvre !",2026-05-23 15:00:00+00:00,Musée Amphoralis,Sallèles-d'Aude,43.262209,2.945924,{}
3,50100,"La classe, l'œuvre ! 2026",2248297,"Mulotia, femme esclavée à l'île Maurice","La classe, l’œuvre !",2026-05-23 15:00:00+00:00,Musée et château royal de Blois,Blois,47.585445,1.331811,{}
4,50100,"La classe, l'œuvre ! 2026",2716271,Visite Flash « C’est moi le guide ! » (FR/EN),"La classe, l’œuvre !",2026-05-23 15:00:00+00:00,Frac Grand Large — Hauts-de-France,Dunkerque,51.048063,2.375820,{}

In [343]:
print("Date min :", df["date"].min())
print("Date max :", df["date"].max())

Date min : 2016-05-26 07:00:00+00:00
Date max : 2027-07-07 09:00:00+00:00

In [344]:
date_limite = pd.Timestamp.now(tz="UTC") - pd.DateOffset(years=1)

df = df[
    df["date"] >= date_limite
]

print(df_final.shape)
print(df_final["date"].min())
print(df_final["date"].max())

(10406, 11)
2025-05-25 13:00:00+00:00
2027-07-07 09:00:00+00:00

In [345]:
df.to_csv(
    "../data/processed/evenements_openagenda_clean.csv",
    index=False
)

print("Dataset sauvegardé : ../data/processed/evenements_openagenda_clean.csv")

Dataset sauvegardé : ../data/processed/evenements_openagenda_clean.csv

In [346]:
df_clean = pd.read_csv("../data/processed/evenements_openagenda_clean.csv")

print("Lignes :", df_clean.shape[0])
print("Colonnes :", df_clean.shape[1])

Lignes : 10406
Colonnes : 11